version: '3'
services:
    app:
        container_name: realtime-api
        restart: always
        build: .
        ports:
            - '8080:3000'
        links:
            - mongo
            - redis-server
    mongo:
        container_name: mongo
        image: mongo
        ports: 
            - '27017:27017'
    redis-server:
        container_name: 'redis-server'
        image: 'redis'
        ports: 
            - '6379:6379'